server:
  port: 8081

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

national-bank-client:
  url: https://api.nbrb.by
  currency-rates-endpoint: /exrates/rates

cache:
  balance:
    ttl: 30
    maximum-size: 10_000