databaseChangeLog:
  - changeSet:
      id: 005-add-uq-account-settings
      author: borisdubinin
      changes:
        - addUniqueConstraint:
            tableName: accounts
            columnNames: settings_id
            constraintName: uq_accounts_settings_id